version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - "9906:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=imagitor
  api:
    build:
      context: "./backend"
    depends_on:
      - mysql_db
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=imagitor 
      - DATABASE_ENGINE=mysql
    ports:
      - "5000:5000"

  client:
    build:
        context: ./frontend
    ports:
      - "5173:80"
      